default: &default
  redis_url: redis://127.0.0.1:6379/0
  concurrency: 5
  queues:
    - critical
    - default
    - low

development: &development
  <<: *default

staging: &staging
  <<: *default

test: &test
  <<: *default

production: &production
  <<: *default